### ISSUE TITLE
could you publish again your grav-plugin-editable repo?

### ISSUE THREAD

**Issue by robinBanquo** [bleutzinn/grav-plugin-editable-simplemde#7] opened 2017-12-21 13:27 UTC
hello
i really appreciate the work on that plugin that offers a nice and user friendly feature.
i've seen on youtuble a vidéo where there is an other plugin that you've maybe done : 
**grav-plugin-editable**
[https://www.youtube.com/watch?v=w8MAdLwV0fE](https://www.youtube.com/watch?v=w8MAdLwV0fE)

someone in the comments advise me to contact you in order to talk with you about it

I want to use, devellop end maintain that nice feature in an open source project, but it seems that the repo has been closed...
**-Could i know the reasons of this?
-are you ok with the fact I continue the dev of this project?**

**Comment by bleutzinn** [comment] 2017-12-21 14:13
Hello Robin,

The reason for removing the repository is that Grav uses Markdown for content and the editor ContentTools can't work with Markdown. ContentTools requires content to be stored in HTML. Grav can do that too, so that is why it all was working fine.

The problem was in that many people were very confused about the switch from Markdown to HTML when using Grav. All Grav documentation focuses on Markdown which becomes useless when you switch to HTML.
Also I could not get an image upload function working from the ContentTools editor, which is, I think, required.

I agree that ContentTools offers a very nice user experience and I would love to see it back with Grav.

So I would be happy if you can take over and improve upon.

It's a two component thing:
Editable (download link <https://warden.stackstorage.com/s/KqI8uvgQidPGcE9>)
ContentTools Add-on (download link <https://warden.stackstorage.com/s/wDfqTA4jH732vSA>)

Please read the ReadMe files carefully and examine the code. As you do, remember I'm not a developer so the code may be terrible. The code of my latest attempt (Editable with SimpleMDE Plugin <https://github.com/bleutzinn/grav-plugin-editable-simplemde>) is better I think and hope...

I suggest you merge these two components into a single plugin. The idea of Add-ons was nice but it gave problems when users updated Editable as it would delete the Add-on which than had to be installed separately by hand.

Many luck with this project!

Cheers,
Ron Wardenier

**Comment by robinBanquo** [comment] 2017-12-21 15:44
I'm very happy to look that you answer my question! thank you very munch for the advices! I'm a young dev , and I will try to do something nice nice and working with what you've done, I have two month of 
traineeship in order to finish my formation and we will see if that will be enouth to publish this very nice plugin again.
In order to help other users that wold want to download your work, take care to delete the last charactere in the link, there is no ">" at the end

**Comment by bleutzinn** [comment] 2017-12-21 16:13
The malformed links were caused by replying via email. Thanks for pointing me to it. I edited my comment so the links should be okay now.

**Comment by bleutzinn** [comment] 2018-03-07 06:56
The two month traineeship you mentioned have passed by now. Can you please give me an update on what you achieved while working on the ContentTools version of Editable ?

**Comment by bleutzinn** [comment] 2018-04-20 20:27
Unfortunately there was no reply from robinBanquo so I'm closing this issue.

**Closed by bleutzinn** 2018-04-20 20:27 UTC
